name: date_picker_pro
description: date_picker_pro,Provide date range select,More will be provided in the future
version: 0.0.4
homepage: https://github.com/LiuDongCai/date_picker_pro

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

